### ISSUE TITLE
little issue with Liu6

### ISSUE THREAD

**Issue by webadi7** [BertJorissen/tmdybinding#4]
Hello, 
first of all thanks for making this package for Pybinding, I was actually implementing Liu6 on it until i found your recent article.

about the issue:  I have a little Problem with the Liu6 implemented right now in TMDybinding, whatever TMD i choose, the band structure, following gamma k m gamma, gives a straight line at 0 eV. also calculating the DOS of a 10*10nm MoS2 flake give a huge DOS value at 0 eV,  i'm pretty sure it's not normal, can you please take a look at it? 
Thanks and have a nice day.
edit, i use  pybinding-dev  1.0.4.post1

**Comment by BertJorissen** [comment]
Hi
I should have expanded the documentation more  https://bertjorissen.github.io/tmdybinding/ .
The pybinding package should also be downloaded from 'pip install pybinding-dev'. Please also check that you do not have the 'normal' pybinding installed ('pip uninstall pybinding').
On the website is a working example (as far as I know).
Can you share a small code example for your issue?
Best
Bert

**Comment by webadi7** [comment]
Thanks for the reply, 
so i checked and only pyb-dev was installed, i uninstalled it and reinstalled it. the same problem occurs
i also uninsatalled tmdybinding and reinstalled it, nothing changed, Also,i'm using Python 3.10.14 
The code :
```
import pybinding as pb
import tmdybinding as tmdy
from tmdybinding.parameters import liu6
from tmdybinding.parameters import wu
from tmdybinding.parameters import fang
import matplotlib.pyplot as plt
import numpy as np

# construct the unit cell,  /!\  please comment one at least
lat = tmdy.TmdNN256Meo(params=tmdy.liu6["MoS2"]).lattice()  # have a straight band at 0 eV
# lat = tmdy.TmdNN256Meo(params=tmdy.wu["MoS2"]).lattice()  # doesn't have a straight band at 0 eV
# make a periodic system
model = pb.Model(lat, pb.translational_symmetry())

# get the parameters
bz = lat.brillouin_zone()
bands = pb.solver.lapack(model).calc_bands(
    bz[3] * 0, bz[3], (bz[3] + bz[4]) / 2, bz[3] * 0
)
plt.figure(2)
bands.plot(point_labels=[r"$\Gamma$", "$K$", "$M$", r"$\Gamma$"])

# get the DOS
solver = pb.solver.lapack(model)
dos = solver.calc_dos(np.linspace(-5, 5, 2000), broadening=0.01)
plt.figure(3)
dos.plot()
```

this is the code i used, at the line "# construct the unit cell", you can comment one of the 2 TB models, Liu6 has a straight line in the band plot  that shouldn't appear, also the DOS of this model show a peak at the same energy as this straight line (0 eV). 
The plots i get :
![Capture d'écran 2024-11-05 130607](https://github.com/user-attachments/assets/3b5e5f0a-c48a-4d0b-8532-e95454104b48)

it's not urgent at all, i just wanted to tell you that this liu6 model didn't give a good results as in the article,  
By the way liu2 (nearest neigbor Mo-Mo) has the same straight line. so idk maybe some matrixes are wrongly calculated? or maybe it's just my python environment that is messed up.
Thanks
Adi

**Comment by BertJorissen** [comment]
Hi
It's actually quite normal.
I didn't explain it in full in the paper, but the classes you use to generate the lattice are dependent on the tight binding model you are using. Because each TB model uses a different basis of orbitals, I have different classes for all these models. You should use the TmdNN256Me class as this implements the toppings for the 2, 5 and 6th nearest neighbour hoppings (between the same 'sublattice' if you would compare with graphene), for the even (e) metal (M) orbitals.
In the new version of pybinding (pybinding-dev), you can also calculate the 'wavefunction' using 'calc_wavefunction()' instead of 'calc_bands()'. Then, you can calculate the 'fatbands' using the 'wfc.fatbands_obrital', and you get the orbital projected band structure. This has some more information about the electronic structure.
The model you used (TmdNN256Meo) also includes the odd energy bands, as proposed in the paper of Wu. As Liu didn't include these parameters, they are zero which appear as vertical lines.
Be careful when calculating the DOS, you should sample the whole Brillouin zone https://bertjorissen.github.io/pybinding/tutorial/wavefunction.html (use calc_wavefunction_area to obtain the projected DOS https://bertjorissen.github.io/pybinding/_api/pybinding.Wavefunction.html).
There is a summary of which class to use to implement which model here: https://bertjorissen.github.io/tmdybinding/documentation/parameters/ .
As far as I'm aware, I implemented all the tight binding models for TMDs (D3h) published in literature that do not use the overlap matrix. If you see some more that could be interesting, let me know and I add them too.

Let me know if you need some more details. A lot of stuff in this package and the updates in pybinding are more internal projects without propper documentation or tutorials. But I'll be happy to add a small example if it helps you.
I'll be in office tomorrow to write a more structured awnser.
Best
Bert

**Comment by webadi7** [comment]
Thanks for the reply,
indeed  Meven 256 are the matrixes needed for Liu, it makes totally sense why it was different, i should have been more carefull when copying code for Wu model. Now i have proper band structure with this model thanks, also the summary of class for different models it's quite practical.
Thanks for the point on the DOS calculation it looked weird and i didn't understood why. The wavefunction is interesting, and I think it would be nice to have a bit more tutorial in the pybinding website for it, to see a bit more how to call it for exemple and what it can do.
I would like to ask some questions about pybinding, especially the calculation of Ldos(r) as i'm trying to do some simulation and i wanted to know if what i'm doing right now with Pb is the most optimal way to do it,  where should i go for asking, is there some kind of forum? 
Thanks again,
Adi

**Comment by BertJorissen** [comment]
For the spatial LDOS you have two options:

- **Exact** calculate the DOS like before, with the full Brillouin Zone, and obtain the spatial LDOS using the wavefunction, https://bertjorissen.github.io/pybinding/_api/pybinding.Wavefunction.html . For the Diagonalization you could also LAPACK (exact, all bands) or ARPACK (more approximate, selected bands). For the ARPACK routine, PyBinding(-dev) has an additional routine that allows you to disentangle the bands. The overlap between the wavefunctions of neighbouring k-points is calculated to obtian the optimal configuration where it seems that you have one band; the (anti)-crossings are correctly resolved within the k-grid.
- **KPM** calculate directly the LDOS using the KPM method. This is faster for larger systems as you don't need the exact diagonalization https://bertjorissen.github.io/pybinding/_api/pybinding.chebyshev.html#pybinding.chebyshev.KPM.calc_spatial_ldos . Also have a look at quantum-kite (pip install quantum-kite - https://quantum-kite.com/) for large-scale (periodic) KPM calculations aimed at HPC.

**Comment by webadi7** [comment]
Thanks for the reply, 
for my usecase, large 2D sheet, KPM method is much better ithink, that's the one i used, but i tought that maybe there was better,
i can't manage to install Kite unfortunately i have some linux problem doing so, i will retry one day on a new docker.
 
So if we stick with Pybinding, and we imagine an non periodic potential distribution applied to a 2d material, V(x,y)
i was wondering if it's possible to multi thread the calculation of Ldos(r) following r. I tried it and got okayish results.

Exemple : let's take a potential distribution V(r) as a gaussian centered in r=0 and from r=20nm the values of V are nearing 0.
I would like to know what is the most optimal way to compute the LDOS at each r position in R (array) using Pybinding for a given energy array.
By optimal i mean minimal computation cost (time, ram usage).
Right now for graphene for exemple, i make a 300 nm side square sheet, and use the kpm.calc_ldos() function for each r in R

300*300 graphene sheet    , broadening 0.02, kpm calc ldos [ from x=0 to x=39 nm ], step 1nm

sequential 1  :                                                                        31 s   0.8gb ram            # @4.3Ghz

sequential 2  + kpm=pb.kpm(model) in "for(r): calc ldos" :  79 s  0.8 gb ram

multithreaded(12c) :                                                              27.5 s   2.7 gb ram        # @2.8-3Ghz
had to put kpm=pb.kpm(model) inside the multithreaded fct, but for sequential it can be used outside of for! 

The 2nd sequential script takes much more time to compute than the 1st one, only thing i changed is where i put kpm=pb.kpm(model) : "out" (1st seq) or "in" (2nd seq) the for loop of ldos(r)
So i _suppose_ it does compute the Chebyshev moment and keep them, and in sequential 1 it just call them back when needed
but i can't "call" the kpm moment calculated with the multithreaded code i wrote, always got a long error, and so had to put kpm=pb.kpm(model) in the multithreaded function.

Is it me imagining that kpm=pb.kpm(model) does compute stuff, and is the kpm to be used for any r posistion?, in this case ldos(r) should be multithreadable? or it's just how kpm(model) is coded that makes kpm=pb.kpm(model) not reusable in multithreaded function following r

Actually i just found about deferred_ldos and  https://bertjorissen.github.io/pybinding/_api/pybinding.parallel.html#module-pybinding.parallel following one of the links you provided, is it possible to use this for multithreading on r array?

Thanks for reading
Best
Adi

the code i used if needed :

```
# -*- coding: utf-8 -*-

import pybinding as pb
import numpy as np
import matplotlib.pyplot as plt
from pybinding.repository import graphene
from timeit import default_timer as timer
import concurrent.futures
import gc

plt.close('all')

@pb.onsite_energy_modifier
def potential_gauss(energy,x, y):
    #print(np.size(x))
    return energy-np.exp(-0.01*(x**2 + y**2))

def rectangle(width, height):
    x0 = width / 2
    y0 = height / 2
    return pb.Polygon([[x0, y0], [x0, -y0], [-x0, -y0], [-x0, y0]])

LONG=300; # nm side lenght graphene sheet
model = pb.Model(
    graphene.monolayer(),
    rectangle(width=LONG, height=LONG),
    potential_gauss)


# # ########### Ldos(r) sequential1 calc of ldos at r ###########################################################################################################################
start = timer()

kpm = pb.kpm(model) # kpm : kernel polynomial method   https://docs.pybinding.site/en/stable/tutorial/kpm.html

x0=0  ## creating the "r" array for LDOS(r)
xend_excl=40 #   xend_excl is last value of LDOS(x) calculated
xstep=1
vectx=np.arange(x0,xend_excl,xstep)
taille=np.size(vectx)

min_E=-1.5  # eV
max_E=1.5
nbr_points=300
energy=np.linspace(min_E, max_E, nbr_points)
resultat=np.zeros((nbr_points,taille))  # saving the LDOS(r) for each r
## @3.9-4.7 Ghz
for x in vectx:
    ldos = kpm.calc_ldos(energy, broadening=0.02, position=[x,0])
    resultat[:,(np.asarray(np.where(vectx==x))[0][0])]=ldos.data    *2/0.052388   *2    *1E18 # ldos class type,  data est ndarray d'est ce qu'il nous faut
                                                        # LDOS in state per eV per m²,  *2 degeneracy spin
    print(x,' nm')

x = vectx
y = np.linspace(min_E, max_E, nbr_points)
X,Y=np.meshgrid(x,y)

plt.figure(1)  ##  LDOS(r)
plt.pcolor(X,Y,resultat)
pb.pltutils.colorbar()
plt.title("LDOS (r nm) sequential")

# plt.figure(2) ## applied Potential 
# y=0
# xx=np.linspace(0,50,201)
# pot=-1*np.exp(-0.01*(xx**2 + y**2))
# plt.plot(xx,pot)
# plt.title("applied potential (r nm)")

print('Sequential time kpm(model) (s)',timer()-start)
print(' ')



# ########### Ldos(r) sequential2   kpm = pb.kpm(model) in the For LOOP ###########################################################################################################################
start = timer()

x0=0  ## creating the "r" array for LDOS(r)
xend_excl=40 #   xend_excl is last value of LDOS(x) calculated
xstep=1
vectx=np.arange(x0,xend_excl,xstep)
taille=np.size(vectx)

min_E=-1.5  # eV
max_E=1.5
nbr_points=300
energy=np.linspace(min_E, max_E, nbr_points)
resultat=np.zeros((nbr_points,taille))  # saving the LDOS(r) for each r
# ## @3.9-4.7 Ghz
for x in vectx:
    kpm = pb.kpm(model)
    ldos = kpm.calc_ldos(energy, broadening=0.02, position=[x,0])
    resultat[:,(np.asarray(np.where(vectx==x))[0][0])]=ldos.data    *2/0.052388   *2    *1E18 # ldos class type,  data est ndarray d'est ce qu'il nous faut
                                                        # LDOS in state per eV per m²,  *2 degeneracy spin
    print(x,' nm')

x = vectx
y = np.linspace(min_E, max_E, nbr_points)
X,Y=np.meshgrid(x,y)

# plt.figure(4)  ##  LDOS(r)
# plt.pcolor(X,Y,resultat)
# pb.pltutils.colorbar()
# plt.title("LDOS (r nm) sequential")

print('Sequential, kpm in for time (s)',timer()-start)
print(' ')






######### Ldos(r) using concurrent threads   #############################################################################################"

start = timer()

# kpm = pb.kpm(model) # kpm : kernel polynomial method   https://docs.pybinding.site/en/stable/tutorial/kpm.html

x0=0  ## creating the "r" array for LDOS(r)
xend_excl=40 #   xend_excl is last value of LDOS(x) calculated
xstep=1
vectx=np.arange(x0,xend_excl,xstep)
taille=np.size(vectx)
min_E=-1.5  # eV
max_E=1.5
nbr_points=300
energy=np.linspace(min_E, max_E, nbr_points)

def ldos_multi(x):
    kpm = pb.kpm(model)
    resultat=np.zeros(nbr_points)         
    ldos = kpm.calc_ldos(energy, broadening=0.02, position=[x,0])
    resultat=ldos.data *2/0.052388   *2    *1E18  # LDOS in state per eV per m²,  *2 degeneracy spin
    # del kpm
    # gc.collect()
    return [resultat,x]

ldos=np.zeros([taille,300])
num_thread=12 
# @2.8-3Ghz or less
if __name__ == '__main__':
    with concurrent.futures.ThreadPoolExecutor(max_workers=num_thread) as executor:
        futures = {executor.submit(ldos_multi,x): x for x in vectx}
        for future in concurrent.futures.as_completed(futures):
            x = futures[future]
            result = future.result()
            z=np.where(result[1]==vectx)[0][0]  # for futur reordering along r increasing
            print(result[1],' nm')
            ldos[z,:] = result[0] 

ldos=np.transpose(ldos)
x = vectx
y = np.linspace(min_E, max_E, nbr_points)
X,Y=np.meshgrid(x,y)

plt.figure(5)  ##  LDOS(r)
plt.pcolor(X,Y,ldos)
pb.pltutils.colorbar()
plt.title("LDOS (r nm) multi")

print('Multi time (s)',timer()-start)
print(' ')

```

**Comment by BertJorissen** [comment]
Hi
You can install kite with 'pip install quantum-kite'.
There is somewhere an example to parallel calculate using the kom method in the API for this deffered function, though I haven't used it a lot. See the small example at https://bertjorissen.github.io/pybinding/_api/pybinding.parallel.html#module-pybinding.parallel . You can also calculate the greens functions using this method.
The 'pb.Model' class is not pickle-able, which is also used by pb.kpm. This means that you have to reconstruct the pb.kpm and pb.Model for each thread.
By now, this crosses the boundary from bugfixes to research. Please cite Pybinding as given in the documentation and also cite my paper https://scipost.org/SciPostPhysCore.7.1.004 if you used my codes.
Happy coding physics!
Best regards
Bert

**Comment by webadi7** [comment]
yep, thanks a lot for all the answers! , i will cite your paper for sure it's quite usefull for TMD,
Have a nice day
Adi
